<?php
declare(strict_types=1);
$root = dirname(__DIR__);
foreach (['config','helpers','db','auth','account_security','learning','notifications','courses','discovery','quiz','editor','serve','security','api','groups','orgs','lti','cc_import','oneroster','backup'] as $name) require_once "$root/sapiqo/app/$name.php";
$checks = 0;
function check(bool $ok, string $message): void {
    global $checks;
    if (!$ok) throw new RuntimeException($message);
    $checks++;
}
ensure_schema();
[$ok, $uid] = register_local(['email'=>'learner@example.org', 'password'=>'Test-password-123']);
check($ok, 'Create learner');
[$ok, $admin] = register_local(['email'=>'admin@example.org', 'password'=>'Admin-password-123', 'role'=>'admin']);
check($ok, 'Create admin');
scan_courses();
$course = course_by_slug('sample'); $cid = (int) $course['id'];
check(isset(record_progress($uid, $cid, 'invented', true)['error']), 'Forged progress rejected');
check(completed_units($uid, $cid) === 0, 'Forged progress cannot affect completion');
check(isset(record_progress($uid, $cid, 'lesson-2', true)['error']), 'Sequential lock enforced');
check(!isset(record_progress($uid, $cid, 'lesson-1', true)['error']), 'Legitimate lesson completion works');
check(course_access_error($uid, $course) === null, 'Published course accessible');
$draft = $course; $draft['status'] = 'draft';
check(course_access_error($uid, $draft) !== null, 'Draft access rejected');
db_run('UPDATE enrollments SET expires_at=? WHERE user_id=? AND course_id=?', ['2020-01-01 00:00:00', $uid, $cid]);
check(course_access_error($uid, $course) !== null, 'Expired enrollment rejected');
db_run('UPDATE enrollments SET expires_at=NULL WHERE user_id=? AND course_id=?', [$uid, $cid]);
$_SESSION = ['uid' => $uid];
$original = course_load_json('sample');
$prepared = quiz_prepare_course($original, $cid);
$quiz = $prepared['modules'][0]['lessons'][0]['quiz'];
check(count($quiz['questions']) === 1, 'Server picks bank size');
$again = quiz_prepare_course($original, $cid);
check($again === $prepared, 'Quiz subset stable across reload');
$public = strip_quiz_answers($prepared);
check(!isset($public['modules'][0]['lessons'][0]['quiz']['questions'][0]['options'][0]['correct']), 'Answer key removed');
$graded = quiz_grade(quiz_find('sample', 'quiz-1'), ['q0'=>[0], 'q1'=>[1]], ['q0','q1']);
check($graded['passed'] && $graded['total'] === 2, 'Correct server grading');
check(!quiz_grade(quiz_find('sample','quiz-1'), ['q0'=>[1], 'q1'=>[0]], ['q0','q1'])['passed'], 'Wrong answers fail');
check(safe_media_ref("java\nscript:alert(1)") === '', 'Control-character URI rejected');
check(!str_contains(cr_inline('[x](javascript:alert(1))'), 'href='), 'Markdown script URL rejected');
check(!str_contains(editor_sanitize_html('<img/onerror=alert(1) src="media/x.png">'), 'onerror'), 'Malformed event handler removed');
check(!str_contains(editor_sanitize_html('<a href="jav&#x61;script:alert(1)">x</a>'), 'href='), 'Entity-obfuscated script removed');
check(!str_contains(editor_sanitize_html('<iframe srcdoc="bad" src="https://example.org"></iframe>'), 'iframe'), 'srcdoc iframe removed');
check(!url_is_safe_public('http://127.0.0.1/'), 'Local SSRF rejected');
check(!url_is_safe_public('http://[::1]/'), 'IPv6 local SSRF rejected');
check(!url_is_safe_public('http://[::ffff:127.0.0.1]/'), 'Mapped local IPv6 rejected');
check(!url_is_safe_public('http://169.254.169.254/'), 'Metadata SSRF rejected');
$_SERVER = ['HTTP_HOST'=>'attacker.invalid', 'SERVER_NAME'=>'localhost', 'SERVER_PORT'=>'8000', 'SCRIPT_NAME'=>'/index.php'];
check(base_url_absolute() === 'http://localhost:8000', 'Host header cannot poison reset links');
$_SERVER['HTTP_X_FORWARDED_PROTO'] = 'https'; $_SERVER['REMOTE_ADDR']='203.0.113.20';
check(!request_is_https(), 'Untrusted forwarded protocol rejected');
$platform = ['issuer'=>'https://platform.example','client_id'=>'client'];
$ltiUser = lti_provision_user(['email'=>'admin@example.org','sub'=>'remote-user',LTI_CLAIM.'roles'=>['Administrator']], $platform);
check($ltiUser['role'] === 'learner' && (int)$ltiUser['id'] !== $admin, 'LTI cannot impersonate or grant local admin');
check(lti_provision_user(['sub'=>'remote-user'], $platform)['id'] === $ltiUser['id'], 'Stable platform identity');
$other = lti_provision_user(['sub'=>'remote-user'], $platform + ['other'=>'unused']);
check($other['id'] === $ltiUser['id'], 'Irrelevant platform fields do not alter identity');
$jwt = jwt_sign(['sub'=>'test']);
check(jwt_verify($jwt, ['public_key'=>lti_keys()['public']]) === null, 'JWT without lifetime rejected');
$jwt = jwt_sign(['sub'=>'test','iat'=>time(),'exp'=>time()+300]);
check(jwt_verify($jwt, ['public_key'=>lti_keys()['public']]) !== null, 'Valid RS256 token accepted');
[$ok, $manager] = register_local(['email'=>'manager@example.org','password'=>'Manager-password-123']);
$group = create_group('Test group');
foreach ([$uid, $admin, $manager] as $member) add_member($group, (int)$member);
add_manager($group, $manager);
check(manager_can_edit_user($manager, $uid), 'Manager can edit a scoped plain learner');
check(!manager_can_edit_user($manager, $admin), 'Manager cannot reset a shared-group admin');
check(!manager_can_edit_user($manager, $manager), 'Scoped editor cannot reset manager accounts');
grant_course_dev($uid);
check(!manager_can_edit_user($manager, $uid), 'Manager cannot reset a course developer');
revoke_course_dev($uid);
$limitedGrade = ['score'=>0,'total'=>1,'passed'=>false];
check(quiz_record_limited($uid, $cid, 'limited-test', $limitedGrade, 1), 'First limited attempt accepted');
check(!quiz_record_limited($uid, $cid, 'limited-test', $limitedGrade, 1), 'Exhausted attempts rejected atomically');
$atomicToken = create_reset_token($uid);
check(reset_password_once($atomicToken, 'Test-password-123'), 'Atomic password reset succeeds');
check(!reset_password_once($atomicToken, 'Attacker-password-123'), 'Atomic reset cannot be replayed');
$token = create_reset_token($uid);
check(user_for_reset_token($token)['id'] === $uid, 'Reset token resolves');
consume_reset_token($token);
check(user_for_reset_token($token) === null, 'Reset token is single-use');
[$keyId, $key] = api_key_create('test', $admin);
$_SERVER['HTTP_AUTHORIZATION']='Bearer '.$key;
check(api_key_check()['id'] === $keyId, 'API token authenticates');
api_key_revoke($keyId);
check(api_key_check() === null, 'Revoked token rejected');
foreach (['good.tar'=>true,'good.tar.gz'=>true,'good.zip'=>true,'traversal.tar'=>false,'absolute.tar'=>false,
    'link.tar'=>false,'traversal.zip'=>false,'link.zip'=>false,'bomb.zip'=>false] as $name=>$expected) {
    check(archive_entries_safe(getenv('SAPIQO_TEST_ARCHIVES').'/'.$name) === $expected, 'Archive validation: '.$name);
}
$report = import_oneroster(getenv('SAPIQO_TEST_ARCHIVES').'/traversal.zip', 'traversal.zip');
check(!empty($report['errors']), 'OneRoster extraction errors are reported');
check(package_file(getenv('SAPIQO_COURSES'), '../../etc/passwd') === null, 'Cartridge manifest cannot read external files');
$report=[];
check(_cc_lesson_content(getenv('SAPIQO_COURSES'), '../config.local.php', getenv('SAPIQO_COURSES'), $report) === '', 'Cartridge missing/traversal gracefully rejected');
$knownSecret = mfa_base32_encode('12345678901234567890');
check(mfa_totp($knownSecret, 1, 8) === '94287082', 'RFC 6238 test vector');
check(mfa_decrypt(mfa_encrypt($knownSecret)) === $knownSecret, 'MFA encryption round trip');
check(mfa_counter($knownSecret, '000000', 59) === null, 'Incorrect TOTP rejected');
db_run('UPDATE users SET mfa_secret=?,mfa_recovery=? WHERE id=?', [mfa_encrypt($knownSecret), json_encode([hash('sha256','recovery-test')]), $manager]);
$code = mfa_totp($knownSecret, intdiv(time(),30));
check(mfa_verify($manager, $code), 'MFA accepts fresh code');
check(!mfa_verify($manager, $code), 'MFA rejects replay');
check(mfa_verify($manager, 'recovery-test') && !mfa_verify($manager, 'recovery-test'), 'Recovery code is single-use');
$_SESSION = ['uid'=>$uid, 'session_version'=>(int)db_one('SELECT session_version FROM users WHERE id=?',[$uid])['session_version']];
check(current_user() !== null, 'Current session authenticates');
revoke_user_sessions($uid);
check(current_user() === null, 'Revoked session rejected');
db_run('UPDATE users SET auth_provider=?,provider_sub=? WHERE id=?',['google','legacy-subject',$manager]);
check(!identity_link($uid,'google','legacy-subject'),'Cannot steal an original provider identity');
db_run('UPDATE users SET auth_provider=?,provider_sub=NULL WHERE id=?',['local',$manager]);
check(identity_link($uid,'test','subject-1') && !identity_link($admin,'test','subject-1'), 'Identity cannot link to two accounts');
[$scopedId, $scopedToken] = api_key_create('read only', $admin, ['courses:read']);
$_SERVER['HTTP_AUTHORIZATION']='Bearer '.$scopedToken; $scoped=api_key_check();
check(api_key_allows($scoped,'courses:read') && !api_key_allows($scoped,'users:write'), 'API scopes bound privileges');
check(learning_utc('2026-10-01T17:00:00-05:00') === '2026-10-01 22:00:00', 'Timezone normalized to UTC');
try { learning_utc('2026-02-30T17:00:00Z'); check(false,'Invalid date rejected'); } catch (InvalidArgumentException $e) { check(true,'Invalid date rejected'); }
check(!empty(course_publication_checks(['slug'=>'empty','title'=>'Empty','modules'=>[]])['errors']), 'Empty course fails publication');
$ac = course_by_slug('assignment'); $acid=(int)$ac['id'];
[$ok,$auid]=register_local(['email'=>'assignment@example.org','password'=>'Assignment-password-123']);
$aid=gb_add_assessment($acid,'Application','Assignment',100,null);
$rubric=rubric_parse("Application | 60\nReflection | 40");
db_run("UPDATE assessments SET submission_enabled=1,required_completion=1,rubric=?,allow_resubmit=1 WHERE id=?",[json_encode($rubric),$aid]);
$a=gb_assessment($aid);
foreach (course_all_step_ids('assignment') as $sid) record_progress($auid,$acid,$sid,true);
check(course_percent($auid,$ac)===75 && !db_one('SELECT id FROM badges WHERE user_id=? AND course_id=?',[$auid,$acid]), 'Required assignment blocks certificate');
assignment_save($a,$auid,'Draft reflection',false,0);
check(assignment_submission($aid,$auid)['status']==='draft','Assignment draft persists');
try { assignment_save($a,$auid,'Stale response',true,0); check(false,'Stale draft rejected'); } catch (InvalidArgumentException $e) { check(true,'Stale draft rejected'); }
assignment_save($a,$auid,'Submitted reflection',true,1);
assignment_grade($a,$auid,2,[30,20],null,'Please revise');
check(course_percent($auid,$ac)===75,'Failing grade blocks completion');
assignment_save($a,$auid,'Improved reflection',true,3);
check(!db_one('SELECT id FROM assessment_scores WHERE assessment_id=? AND user_id=?',[$aid,$auid]), 'Resubmission clears old score');
assignment_grade($a,$auid,4,[60,40],null,'Well done');
check(course_percent($auid,$ac)===100 && (bool)db_one('SELECT id FROM badges WHERE user_id=? AND course_id=?',[$auid,$acid]),'Passing rubric issues credential');
try { assignment_grade($a,$auid,4,[60,40],null,'Stale grade'); check(false,'Stale grading rejected'); } catch (InvalidArgumentException $e) { check(true,'Stale grading rejected'); }
$ag=create_group('Assignment cohort'); add_member($ag,$auid);
db_run("INSERT INTO cohort_schedules (group_id,course_id,opens_at,due_at,late_policy) VALUES (?,?,?,?,?)",[$ag,$acid,'2099-01-01 00:00:00','2099-01-02 00:00:00','accept']);
check(course_access_error($auid,$ac)!==null,'Future cohort cannot access course');
db_run('UPDATE cohort_schedules SET opens_at=NULL,due_at=?,late_policy=? WHERE group_id=? AND course_id=?',['2000-01-01 00:00:00','close',$ag,$acid]);
check(assignment_due($a,$auid)==='2000-01-01 00:00:00','Cohort overrides assignment deadline');
try { assignment_save($a,$auid,'Late',true,5); check(false,'Closed late submission rejected'); } catch (InvalidArgumentException $e) { check(true,'Closed late submission rejected'); }
db_run('DELETE FROM cohort_schedules WHERE group_id=? AND course_id=?',[$ag,$acid]);
check(!assignment_can_grade($acid,$manager),'Content access does not imply student-work access');
db_run('INSERT INTO course_instructors (course_id,user_id) VALUES (?,?)',[$acid,$manager]);
check(assignment_can_grade($acid,$manager) && !assignment_can_grade($cid,$manager),'Instructor access is course-scoped');
$backup = create_backup(getenv('SAPIQO_DATA').'/backups');
check(archive_entries_safe($backup), 'Backup passes archive validation');
$backupContents = new PharData($backup);
check(isset($backupContents['db/snapshot.sqlite']), 'Backup contains SQLite snapshot');
$restoredFile = getenv('SAPIQO_DATA').'/snapshot-check.sqlite';
file_put_contents($restoredFile, $backupContents['db/snapshot.sqlite']->getContent());
$snapshotDb = new PDO('sqlite:'.$restoredFile);
check($snapshotDb->query('PRAGMA integrity_check')->fetchColumn() === 'ok', 'Backup snapshot integrity');
check((int) $snapshotDb->query('SELECT COUNT(*) FROM users')->fetchColumn() >= 3, 'Snapshot retains users');
unlink($restoredFile);
echo "$checks security regression checks passed\n";
