<?php
declare(strict_types=1);
$root = dirname(__DIR__);
foreach (['config','helpers','db','auth','courses','discovery','quiz','editor','serve','security','api','groups','orgs','lti','cc_import','oneroster','backup'] as $name) require_once "$root/sapiqo/app/$name.php";
$checks = 0;
function check(bool $ok, string $message): void {
    global $checks;
    if (!$ok) throw new RuntimeException($message);
    $checks++;
}
ensure_schema();
[$ok, $uid] = register_local(['email'=>'learner@example.org', 'password'=>'Test-password-123']);
check($ok, 'Create learner');
[$ok, $admin] = register_local(['email'=>'admin@example.org', 'password'=>'Admin-password-123', 'role'=>'admin']);
check($ok, 'Create admin');
scan_courses();
$course = course_by_slug('sample'); $cid = (int) $course['id'];
check(isset(record_progress($uid, $cid, 'invented', true)['error']), 'Forged progress rejected');
check(completed_units($uid, $cid) === 0, 'Forged progress cannot affect completion');
check(isset(record_progress($uid, $cid, 'lesson-2', true)['error']), 'Sequential lock enforced');
check(!isset(record_progress($uid, $cid, 'lesson-1', true)['error']), 'Legitimate lesson completion works');
check(course_access_error($uid, $course) === null, 'Published course accessible');
$draft = $course; $draft['status'] = 'draft';
check(course_access_error($uid, $draft) !== null, 'Draft access rejected');
db_run('UPDATE enrollments SET expires_at=? WHERE user_id=? AND course_id=?', ['2020-01-01 00:00:00', $uid, $cid]);
check(course_access_error($uid, $course) !== null, 'Expired enrollment rejected');
db_run('UPDATE enrollments SET expires_at=NULL WHERE user_id=? AND course_id=?', [$uid, $cid]);
$_SESSION = ['uid' => $uid];
$original = course_load_json('sample');
$prepared = quiz_prepare_course($original, $cid);
$quiz = $prepared['modules'][0]['lessons'][0]['quiz'];
check(count($quiz['questions']) === 1, 'Server picks bank size');
$again = quiz_prepare_course($original, $cid);
check($again === $prepared, 'Quiz subset stable across reload');
$public = strip_quiz_answers($prepared);
check(!isset($public['modules'][0]['lessons'][0]['quiz']['questions'][0]['options'][0]['correct']), 'Answer key removed');
$graded = quiz_grade(quiz_find('sample', 'quiz-1'), ['q0'=>[0], 'q1'=>[1]], ['q0','q1']);
check($graded['passed'] && $graded['total'] === 2, 'Correct server grading');
check(!quiz_grade(quiz_find('sample','quiz-1'), ['q0'=>[1], 'q1'=>[0]], ['q0','q1'])['passed'], 'Wrong answers fail');
check(safe_media_ref("java\nscript:alert(1)") === '', 'Control-character URI rejected');
check(!str_contains(cr_inline('[x](javascript:alert(1))'), 'href='), 'Markdown script URL rejected');
check(!str_contains(editor_sanitize_html('<img/onerror=alert(1) src="media/x.png">'), 'onerror'), 'Malformed event handler removed');
check(!str_contains(editor_sanitize_html('<a href="jav&#x61;script:alert(1)">x</a>'), 'href='), 'Entity-obfuscated script removed');
check(!str_contains(editor_sanitize_html('<iframe srcdoc="bad" src="https://example.org"></iframe>'), 'iframe'), 'srcdoc iframe removed');
check(!url_is_safe_public('http://127.0.0.1/'), 'Local SSRF rejected');
check(!url_is_safe_public('http://[::1]/'), 'IPv6 local SSRF rejected');
check(!url_is_safe_public('http://[::ffff:127.0.0.1]/'), 'Mapped local IPv6 rejected');
check(!url_is_safe_public('http://169.254.169.254/'), 'Metadata SSRF rejected');
$_SERVER = ['HTTP_HOST'=>'attacker.invalid', 'SERVER_NAME'=>'localhost', 'SERVER_PORT'=>'8000', 'SCRIPT_NAME'=>'/index.php'];
check(base_url_absolute() === 'http://localhost:8000', 'Host header cannot poison reset links');
$_SERVER['HTTP_X_FORWARDED_PROTO'] = 'https'; $_SERVER['REMOTE_ADDR']='203.0.113.20';
check(!request_is_https(), 'Untrusted forwarded protocol rejected');
$platform = ['issuer'=>'https://platform.example','client_id'=>'client'];
$ltiUser = lti_provision_user(['email'=>'admin@example.org','sub'=>'remote-user',LTI_CLAIM.'roles'=>['Administrator']], $platform);
check($ltiUser['role'] === 'learner' && (int)$ltiUser['id'] !== $admin, 'LTI cannot impersonate or grant local admin');
check(lti_provision_user(['sub'=>'remote-user'], $platform)['id'] === $ltiUser['id'], 'Stable platform identity');
$other = lti_provision_user(['sub'=>'remote-user'], $platform + ['other'=>'unused']);
check($other['id'] === $ltiUser['id'], 'Irrelevant platform fields do not alter identity');
$jwt = jwt_sign(['sub'=>'test']);
check(jwt_verify($jwt, ['public_key'=>lti_keys()['public']]) === null, 'JWT without lifetime rejected');
$jwt = jwt_sign(['sub'=>'test','iat'=>time(),'exp'=>time()+300]);
check(jwt_verify($jwt, ['public_key'=>lti_keys()['public']]) !== null, 'Valid RS256 token accepted');
[$ok, $manager] = register_local(['email'=>'manager@example.org','password'=>'Manager-password-123']);
$group = create_group('Test group');
foreach ([$uid, $admin, $manager] as $member) add_member($group, (int)$member);
add_manager($group, $manager);
check(manager_can_edit_user($manager, $uid), 'Manager can edit a scoped plain learner');
check(!manager_can_edit_user($manager, $admin), 'Manager cannot reset a shared-group admin');
check(!manager_can_edit_user($manager, $manager), 'Scoped editor cannot reset manager accounts');
grant_course_dev($uid);
check(!manager_can_edit_user($manager, $uid), 'Manager cannot reset a course developer');
revoke_course_dev($uid);
$limitedGrade = ['score'=>0,'total'=>1,'passed'=>false];
check(quiz_record_limited($uid, $cid, 'limited-test', $limitedGrade, 1), 'First limited attempt accepted');
check(!quiz_record_limited($uid, $cid, 'limited-test', $limitedGrade, 1), 'Exhausted attempts rejected atomically');
$atomicToken = create_reset_token($uid);
check(reset_password_once($atomicToken, 'Test-password-123'), 'Atomic password reset succeeds');
check(!reset_password_once($atomicToken, 'Attacker-password-123'), 'Atomic reset cannot be replayed');
$token = create_reset_token($uid);
check(user_for_reset_token($token)['id'] === $uid, 'Reset token resolves');
consume_reset_token($token);
check(user_for_reset_token($token) === null, 'Reset token is single-use');
[$keyId, $key] = api_key_create('test', $admin);
$_SERVER['HTTP_AUTHORIZATION']='Bearer '.$key;
check(api_key_check()['id'] === $keyId, 'API token authenticates');
api_key_revoke($keyId);
check(api_key_check() === null, 'Revoked token rejected');
foreach (['good.tar'=>true,'good.tar.gz'=>true,'good.zip'=>true,'traversal.tar'=>false,'absolute.tar'=>false,
    'link.tar'=>false,'traversal.zip'=>false,'link.zip'=>false,'bomb.zip'=>false] as $name=>$expected) {
    check(archive_entries_safe(getenv('SAPIQO_TEST_ARCHIVES').'/'.$name) === $expected, 'Archive validation: '.$name);
}
$report = import_oneroster(getenv('SAPIQO_TEST_ARCHIVES').'/traversal.zip', 'traversal.zip');
check(!empty($report['errors']), 'OneRoster extraction errors are reported');
check(package_file(getenv('SAPIQO_COURSES'), '../../etc/passwd') === null, 'Cartridge manifest cannot read external files');
$report=[];
check(_cc_lesson_content(getenv('SAPIQO_COURSES'), '../config.local.php', getenv('SAPIQO_COURSES'), $report) === '', 'Cartridge missing/traversal gracefully rejected');
$backup = create_backup(getenv('SAPIQO_DATA').'/backups');
check(archive_entries_safe($backup), 'Backup passes archive validation');
$backupContents = new PharData($backup);
check(isset($backupContents['data-root/data/lms.sqlite']), 'Backup contains SQLite snapshot');
$restoredFile = getenv('SAPIQO_DATA').'/snapshot-check.sqlite';
file_put_contents($restoredFile, $backupContents['data-root/data/lms.sqlite']->getContent());
$snapshotDb = new PDO('sqlite:'.$restoredFile);
check($snapshotDb->query('PRAGMA integrity_check')->fetchColumn() === 'ok', 'Backup snapshot integrity');
check((int) $snapshotDb->query('SELECT COUNT(*) FROM users')->fetchColumn() >= 3, 'Snapshot retains users');
unlink($restoredFile);
echo "$checks security regression checks passed\n";
