<div class="page-head"><h1>Account security</h1><p><a href="<?= e(url('/profile')) ?>">Back to profile</a></p></div>
<?php if ($recovery): ?><div class="card" role="status"><h2>Save your recovery codes</h2><p>Each code works once. Keep these somewhere safe; they will not be shown again.</p><pre><?= e(implode("\n", $recovery)) ?></pre></div><?php endif; ?>
<div class="card"><h2>Two-step verification</h2>
<?php if (!empty($user['mfa_secret'])): ?><p>Enabled. Sign-in requires your authenticator or a recovery code.</p>
<?php else: ?><p>Add this secret to an authenticator app using a time-based, six-digit code (SHA-1, 30 seconds).</p><div class="field"><label for="secret">Authenticator secret</label><input id="secret" readonly value="<?= e($setup) ?>" data-select-all></div><?php endif; ?>
<form method="post" action="<?= e(url('/profile/security')) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="<?= empty($user['mfa_secret']) ? 'enable' : 'disable' ?>">
<?php if (empty($user['mfa_secret'])): ?><div class="field"><label for="setup_code">Code from your new authenticator</label><input id="setup_code" name="setup_code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></div><?php endif; ?>
<?php $prefix='mfa'; require __DIR__ . '/security_confirm.php'; ?><button class="btn btn-outline" type="submit"><?= empty($user['mfa_secret']) ? 'Enable two-step verification' : 'Disable two-step verification' ?></button></form></div>
<div class="card"><h2>Sign out all sessions</h2><p>This also signs out this browser. Password changes automatically revoke existing sessions.</p><form method="post" action="<?= e(url('/profile/security')) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="revoke"><?php $prefix='sessions'; require __DIR__ . '/security_confirm.php'; ?><button class="btn btn-outline" type="submit">Sign out all sessions</button></form></div>
<div class="card"><h2>Additional sign-in methods</h2><p>Confirm your current account, then authenticate with the provider to link it. Accounts are never linked automatically by email.</p>
<?php foreach ($providers as $provider => $details): ?><form method="post" action="<?= e(url('/profile/security')) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="link"><input type="hidden" name="provider" value="<?= e($provider) ?>"><?php $prefix='link-'.$provider; require __DIR__ . '/security_confirm.php'; ?><button class="btn btn-outline" type="submit">Link <?= e($details['label']) ?></button></form><?php endforeach; ?>
<?php if (!$providers): ?><p>No external providers are configured.</p><?php endif; ?>
<?php foreach ($identities as $identity): ?><form method="post" action="<?= e(url('/profile/security')) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="unlink"><input type="hidden" name="provider" value="<?= e($identity['provider']) ?>"><?php $prefix='unlink-'.$identity['provider']; require __DIR__ . '/security_confirm.php'; ?><button class="btn btn-outline" type="submit">Unlink <?= e($identity['provider']) ?></button></form><?php endforeach; ?></div>
