<div class="page-head"><h1>Assignments: <?= e($course['title']) ?></h1><p><a href="<?= e(url('/learn/'.$course['slug'])) ?>">Return to course</a> · <a href="<?= e(url('/dashboard')) ?>">Dashboard</a></p><p>Required assignments need a passing instructor grade before a new certificate is issued. Dates are shown in UTC.</p></div>
<?php if (!$assignments): ?><div class="card"><p>No assignments have been added.</p></div><?php endif; ?>
<?php foreach ($assignments as $a): $sub=assignment_submission((int)$a['id'],$uid); $due=assignment_due($a,$uid); $rubric=json_decode($a['rubric']?:'[]',true); $prefix='a-'.$a['id']; ?>
<section class="card" aria-labelledby="<?= e($prefix) ?>-title"><h2 id="<?= e($prefix) ?>-title"><?= e($a['title']) ?></h2><p><strong><?= !empty($a['required_completion'])?'Required':'Optional' ?></strong> · <?= e(gb_num($a['max_points'])) ?> points · Passing: <?= e(gb_num($a['pass_percent'])) ?>% · Status: <?= e($sub['status']??'Not started') ?></p>
<?php if ($due): ?><p>Due: <time><?= e($due) ?> UTC</time><?= $due<now_utc()?' (past deadline)':'' ?> · <?= $a['late_policy']==='close'?'Late submissions closed':'Late submissions accepted' ?></p><?php endif; ?>
<?php if (!assignment_is_available($a,$uid)): ?><p>This assignment has not opened yet.</p><?php else: ?>
<p style="white-space:pre-wrap"><?= e($a['instructions']) ?></p>
<?php if ($rubric): ?><h3>Rubric</h3><ul><?php foreach ($rubric as $c): ?><li><?= e($c['title']) ?> — <?= e(gb_num($c['max'])) ?> points</li><?php endforeach; ?></ul><?php endif; ?>
<?php if ($sub && $sub['status']==='graded'): $score=db_one('SELECT points FROM assessment_scores WHERE assessment_id=? AND user_id=?',[$a['id'],$uid]); ?><h3>Instructor feedback</h3><p>Score: <?= e(gb_num($score['points']??null)) ?> / <?= e(gb_num($a['max_points'])) ?></p><p style="white-space:pre-wrap"><?= e($sub['feedback']) ?></p><?php foreach (json_decode($sub['rubric_scores']?:'[]',true) as $c): ?><p><?= e($c['title']) ?>: <?= e(gb_num($c['points'])) ?> / <?= e(gb_num($c['max'])) ?></p><?php endforeach; ?><?php endif; ?>
<?php if (!$sub || $sub['status']==='draft' || !empty($a['allow_resubmit'])): ?>
<form method="post" enctype="multipart/form-data" action="<?= e(url('/assignments/'.$course['slug'].'/'.$a['id'])) ?>"><?= csrf_field() ?><input type="hidden" name="revision" value="<?= (int)($sub['revision']??0) ?>"><div class="field"><label for="<?= e($prefix) ?>-body">Your response</label><textarea id="<?= e($prefix) ?>-body" name="body" rows="8" maxlength="100000" style="width:100%"><?= e($sub['body']??'') ?></textarea></div><div class="field"><label for="<?= e($prefix) ?>-file">Attach or replace a file (optional)</label><input id="<?= e($prefix) ?>-file" type="file" name="file" accept=".pdf,.txt,.png,.jpg,.jpeg"><small>PDF, plain text, PNG or JPEG; maximum 10 MB.</small></div><p>Saving or resubmitting a graded response clears its current score for review. Existing transcript credentials remain.</p><button class="btn btn-outline" name="action" value="draft" type="submit">Save draft</button> <button class="btn btn-gold" name="action" value="submit" type="submit">Submit for review</button></form>
<?php else: ?><p>Resubmission is disabled. Contact your instructor if you need changes.</p><?php endif; ?>
<?php if (!empty($sub['file_path'])): ?><p><a href="<?= e(url('/assignment-file/'.$sub['id'])) ?>">Download your attachment: <?= e($sub['file_name']) ?></a></p><?php endif; ?>
<?php endif; ?></section><?php endforeach; ?>
